/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examenip2_nahimhilsaca;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author nahim
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tabbed = new javax.swing.JTabbedPane();
        equipo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nom_equipo = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pais_equipo = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        estadio = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        nom_estadio = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        cb_equipoestadio = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jugador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        t_nombre = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        t_edad = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        t_nacionalidad = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        t_pie = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_equipo = new javax.swing.JComboBox<>();
        Buton_jugador = new javax.swing.JButton();
        cb_posicion = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setText("Ingrese su Nombre:");

        nom_equipo.setColumns(20);
        nom_equipo.setRows(5);
        jScrollPane1.setViewportView(nom_equipo);

        jLabel3.setText("Ingrese su Pais");

        pais_equipo.setColumns(20);
        pais_equipo.setRows(5);
        pais_equipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pais_equipoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pais_equipo);

        jButton1.setText("Agregar Equipo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout equipoLayout = new javax.swing.GroupLayout(equipo);
        equipo.setLayout(equipoLayout);
        equipoLayout.setHorizontalGroup(
            equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(151, 151, 151))
            .addGroup(equipoLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(369, Short.MAX_VALUE))
        );
        equipoLayout.setVerticalGroup(
            equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(equipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
        );

        tabbed.addTab("Agregar Equipo", equipo);

        jLabel8.setText("Nombre");

        nom_estadio.setColumns(20);
        nom_estadio.setRows(5);
        jScrollPane8.setViewportView(nom_estadio);

        jLabel10.setText("Ciudad");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane9.setViewportView(jTextArea1);

        jLabel11.setText("Equipo");

        cb_equipoestadio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipos" }));
        cb_equipoestadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_equipoestadioMouseClicked(evt);
            }
        });

        jButton2.setText("Agregar Estadio");

        javax.swing.GroupLayout estadioLayout = new javax.swing.GroupLayout(estadio);
        estadio.setLayout(estadioLayout);
        estadioLayout.setHorizontalGroup(
            estadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estadioLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(estadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addGroup(estadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane9)
                    .addComponent(cb_equipoestadio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(160, 160, 160))
            .addGroup(estadioLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        estadioLayout.setVerticalGroup(
            estadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estadioLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(estadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(estadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(estadioLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(estadioLayout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb_equipoestadio)))
                .addGap(51, 51, 51)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        tabbed.addTab("Agregar Estadio", estadio);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 943, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );

        tabbed.addTab("Listar Todo", jPanel3);

        jLabel1.setText("Nombre:");

        t_nombre.setColumns(20);
        t_nombre.setRows(5);
        jScrollPane3.setViewportView(t_nombre);

        jLabel4.setText("Edad:");

        t_edad.setColumns(20);
        t_edad.setRows(5);
        jScrollPane4.setViewportView(t_edad);

        jLabel5.setText("Nacionalidad:");

        t_nacionalidad.setColumns(20);
        t_nacionalidad.setRows(5);
        jScrollPane5.setViewportView(t_nacionalidad);

        jLabel6.setText("Pie Habil:");

        t_pie.setColumns(20);
        t_pie.setRows(5);
        t_pie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_pieMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                t_pieMouseExited(evt);
            }
        });
        jScrollPane6.setViewportView(t_pie);

        jLabel7.setText("Posicion del Jugador:");

        jLabel9.setText("Equipo");

        cb_equipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipos" }));
        cb_equipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_equipoMouseClicked(evt);
            }
        });

        Buton_jugador.setText("Agregar Jugador");
        Buton_jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buton_jugadorActionPerformed(evt);
            }
        });

        cb_posicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portero", "Defensa", "Mediocampista", "Delantero" }));
        cb_posicion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_posicionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jugadorLayout = new javax.swing.GroupLayout(jugador);
        jugador.setLayout(jugadorLayout);
        jugadorLayout.setHorizontalGroup(
            jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jugadorLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addGroup(jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cb_equipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cb_posicion, 0, 221, Short.MAX_VALUE))
                .addGap(190, 190, 190))
            .addGroup(jugadorLayout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(Buton_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jugadorLayout.setVerticalGroup(
            jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jugadorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jugadorLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jugadorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jugadorLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jugadorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jugadorLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cb_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_equipo, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addComponent(Buton_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tabbed.addTab("Agregar Jugador", jugador);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(tabbed, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tabbed)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pais_equipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pais_equipoMouseClicked
        
    }//GEN-LAST:event_pais_equipoMouseClicked

    private void t_pieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_pieMouseClicked
        
    }//GEN-LAST:event_t_pieMouseClicked

    private void t_pieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_pieMouseExited
        if (t_pie.getText().equalsIgnoreCase("izquierdo")|| t_pie.getText().equalsIgnoreCase("derecho")) {
            t_pie.setText("");
            JOptionPane.showConfirmDialog(this, "Excelente pie");
        } else {
             t_pie.setText("");
            JOptionPane.showConfirmDialog(null, "Solo puede poner si su pie es derecho o izquiero");
        }
    }//GEN-LAST:event_t_pieMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        equipos.add(new Equipo(nom_equipo.getText(),pais_equipo.getText()));
        DefaultComboBoxModel modelo= (DefaultComboBoxModel)cb_equipo.getModel();
        for (int i = 0; i < equipos.size(); i++) {
            modelo.addElement(equipos.get(i));
        }
        cb_equipo.setModel(modelo);
  
    }//GEN-LAST:event_jButton1MouseClicked

    private void Buton_jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buton_jugadorActionPerformed
           
        String posicion= cb_posicion.getSelectedItem().toString();
        
        
        if ("Portero".equals(posicion)) {
            
            String nombre= t_nombre.getText();
            int edad=Integer.parseInt(t_edad.getText());
            String nacionalidad= t_nacionalidad.getText();
            String habil= t_pie.getText();
            Equipo equipojugador= (Equipo)cb_equipo.getSelectedItem();
            
            jugadores.add(new Portero(nombre,edad,nacionalidad,habil,equipojugador)); 
            

        }else if("Defensa".equals(posicion)){
            String nombre= t_nombre.getText();
            int edad=Integer.parseInt(t_edad.getText());
            String nacionalidad= t_nacionalidad.getText();
            String habil= t_pie.getText();
            Equipo equipojugador= (Equipo)cb_equipo.getSelectedItem();
            
            jugadores.add(new Defensa(nombre,edad,nacionalidad,habil,equipojugador)); 
            
        
        
        
        
        }else if("Mediocampista".equals(posicion)){
        
         String nombre= t_nombre.getText();
            int edad=Integer.parseInt(t_edad.getText());
            String nacionalidad= t_nacionalidad.getText();
            String habil= t_pie.getText();
            Equipo equipojugador= (Equipo)cb_equipo.getSelectedItem();
            
            jugadores.add(new Mediocampista(nombre,edad,nacionalidad,habil,equipojugador)); 
            
        }else if("Delantero".equals(posicion)){
            String nombre= t_nombre.getText();
            int edad=Integer.parseInt(t_edad.getText());
            String nacionalidad= t_nacionalidad.getText();
            String habil= t_pie.getText();
            Equipo equipojugador= (Equipo)cb_equipo.getSelectedItem();
            
            jugadores.add(new Delantero(nombre,edad,nacionalidad,habil,equipojugador)); 
        
        
        
        }
            
    }//GEN-LAST:event_Buton_jugadorActionPerformed

    private void cb_posicionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_posicionMouseClicked
        
        
        for (int i = 0; i < equipos.size()
                ; i++) {
             String equipo= equipos.get(i).getNombre_equipo().toString();
            equipo= cb_equipo.getSelectedItem().toString();
            
        }

    }//GEN-LAST:event_cb_posicionMouseClicked

    private void cb_equipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_equipoMouseClicked
        for (int i = 0; i < equipos.size()
                ; i++) {
            
            String equipo= equipos.get(i).getNombre_equipo().toString();
            equipo= cb_equipo.getSelectedItem().toString();
            
        }
    }//GEN-LAST:event_cb_equipoMouseClicked

    private void cb_equipoestadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_equipoestadioMouseClicked
         equipos.add(new Equipo(nom_equipo.getText(),pais_equipo.getText()));
        DefaultComboBoxModel modelo= (DefaultComboBoxModel)cb_equipo.getModel();
        for (int i = 0; i < equipos.size(); i++) {
            modelo.addElement(equipos.get(i));
        }
        cb_equipo.setModel(modelo);
    }//GEN-LAST:event_cb_equipoestadioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    ArrayList<Jugador> jugadores= new ArrayList<>();
ArrayList  <Equipo> equipos= new ArrayList();
ArrayList <Estadio> estadios= new ArrayList();
Jugador j;
Equipo w= new Equipo();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buton_jugador;
    private javax.swing.JComboBox<String> cb_equipo;
    private javax.swing.JComboBox<String> cb_equipoestadio;
    private javax.swing.JComboBox<String> cb_posicion;
    private javax.swing.JPanel equipo;
    private javax.swing.JPanel estadio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel jugador;
    private javax.swing.JTextArea nom_equipo;
    private javax.swing.JTextArea nom_estadio;
    private javax.swing.JTextArea pais_equipo;
    private javax.swing.JTextArea t_edad;
    private javax.swing.JTextArea t_nacionalidad;
    private javax.swing.JTextArea t_nombre;
    private javax.swing.JTextArea t_pie;
    private javax.swing.JTabbedPane tabbed;
    // End of variables declaration//GEN-END:variables
}
